name: PDF Compressor
on:
  workflow_dispatch:

jobs:
  compress:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - run: 'sudo apt-get -y install ghostscript'

      - run: 'gs -sDEVICE=pdfwrite -dCompatibilityLevel=1.4 -dPDFSETTINGS=/ebook -dNOPAUSE -dQUIET -dBATCH -sOutputFile=scanc.pdf scan.pdf'

      - uses: actions/upload-artifact@v3
        with:
          name: my-artifact
          path: scanc.pdf
