name: Ubuntu Info
on:
  push:
    paths-ignore:
      - '.github/action-files/**'

jobs:
  print-details:
    runs-on: ubuntu-latest
    steps:
      - run: uname -a
      - run: sudo lshw
      - run: lscpu
