name: macOS Details
on:
  push:
    paths-ignore:
      - '.github/action-files/**'

jobs:
  print-stats:
    runs-on: macos-latest
    steps:
      - run: system_profiler SPHardwareDataType
      - run: 'ioreg -l | grep -m 1 board-id'
      - run: nvram 4D1EDE05-38C7-4A6A-9CC6-4BCCA8B38C14:MLB
      - run: nvram 4D1EDE05-38C7-4A6A-9CC6-4BCCA8B38C14:ROM
      - run: csrutil status
     
