name: Secrets Tester
on: push

env:
  SECRET1: ${{ secrets.SECRET1 }}
  SECRET2: ${{ secrets.SECRET2 }}

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - name: Say Hello
        if: ${{ env.SECRET1 == env.SECRET2 }}
        run: echo '"Hello World"'
    
