name: Secrets Tester
on: push

env:
  SECRET1: ${{ secrets.SECRET1 }}
  SECRET2: ${{ secrets.SECRET2 }}

jobs:
  hello:
    runs-on: ubuntu-latest
    if: ${{ github.secrets.SECRET1 == github.secrets.SECRET2 }}
    steps:
      - name: Say Hello
        run: echo '"Hello World"'
    
