name: Secrets Tester
on: push

jobs:
  hello:
    runs-on: ubuntu-latest
    if: ${{ github.secrets.SECRET1 == github.secrets.SECRET2 }}
    steps:
      - name: Say Hello
        run: echo '"Hello World"'
    
