name: Update branches on GH Docs Repo Pulls
on:
  schedule:
    - cron: '*/20 * * * *'
    
jobs:
  get-lastsha:
    runs-on: ubuntu-latest
    outputs:
      sha: ${{ steps.raw-file.outputs.file }}
      filesha: ${{ steps.file-sha.outputs.filesha }}
    steps:
      - name: Get latest Commit sha according to actions.
        id: latest-sha-updated
        uses: octokit/request-action@v2.x
        with:
          route: GET repos/{owner}/{repo}/contents/{path}
          owner: thispsj
          repo: actions-lab
          path: .github/action-files/commitsha
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Set File SHA
        id: file-sha
        run: echo "::set-output name=filesha::$FSHA"
        env:
          FSHA: ${{ fromJSON(steps.latest-sha-updated.outputs.data).sha }}
      - name: Get the raw file.
        id: raw-file
        run: ' export FILE=`echo $ENCFILE | base64 -d` && echo "::set-output name=file::$FILE" '
        env:
          ENCFILE: ${{ fromJSON(steps.latest-sha-updated.outputs.data).content }}
        
  
  update-branch:
    needs: get-lastsha
    runs-on: ubuntu-latest
    outputs:
      data: ${{ steps.get-pull.outputs.data }}
    strategy:
      matrix:
        number: [8982]
    steps:
      - name: Output ok to stdout
        id: run-or-not
        run: echo "::set-output name=go-ahead::ok"
      - name: Get Pull Request
        uses: octokit/request-action@v2.x
        id: get-pull
        if: ${{ steps.run-or-not.outputs.go-ahead == 'ok' }}
        with:
          route: GET /repos/{owner}/{repo}/pulls/{pull_number}
          owner: github
          repo: docs
          pull_number: ${{ matrix.number }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Update Branch to latest base ref
        if: ${{ steps.run-or-not.outputs.go-ahead == 'ok' && needs.get-lastsha.outputs.sha != fromJSON(steps.get-pull.outputs.data).base.sha }}
        uses: octokit/request-action@v2.x
        id: update-pullbranch-api
        with:
          route: PUT /repos/{owner}/{repo}/pulls/{pull_number}/update-branch
          owner: github
          repo: docs
          pull_number: ${{ matrix.number }}
          mediaType: '{"previews":["lydian"]}'
        env:
          GITHUB_TOKEN: ${{ secrets.GHPAT }} # expires on 3rd Jan 22. please remember to refresh.
  update-sha:
    needs: [get-lastsha,update-branch]
    runs-on: ubuntu-latest
    if: ${{ fromJSON(needs.update-branch.outputs.data).base.sha != needs.get-lastsha.outputs.sha }}
    jobs:
      - name: Encode to Base64
        id: encsha
        run: ' export ESHA=`echo $BSHA | base64` && echo "::set-output name=esha::$ESHA" '
        env:
          BSHA: ${{ fromJSON(needs.update-branch.outputs.data).base.sha }}
      - name: Update File
        uses: octokit/request-action@v2.x
        with:
          route: PUT /repos/{owner}/{repo}/contents/{path}
          owner: thispsj
          repo: actions-lab
          path: .github/action-files/commitsha
          message: Update Base branch SHA
          sha: ${{ needs.get-lastsha.outputs.filesha }}
          content: ${{ steps.encsha.outputs.esha }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  
  
