name: Update branches on GH Docs Repo Pulls
on:
  schedule:
    - cron: '20,35,50,05 * * * *'
    
jobs:
  get-lastsha:
    runs-on: ubuntu-latest
    outputs:
      mainsha: ${{ fromJSON(steps.main-sha.outputs.data).commit.sha }}
    steps:
      - name: Get docs main sha
        id: main-sha
        uses: octokit/request-action@v2.x
        with:
          route: GET /repos/{owner}/{repo}/branches/{branch}
          owner: github
          repo: docs
          branch: main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  update-branch:
    needs: get-lastsha
    runs-on: ubuntu-latest
    strategy:
      matrix:
        number: [9126,9119]
    steps:
      - name: Output ok to stdout
        id: run-or-not
        run: echo "::set-output name=go-ahead::ok"
      - name: Get Pull Request
        uses: octokit/request-action@v2.x
        id: get-pull
        if: ${{ steps.run-or-not.outputs.go-ahead == 'ok' }}
        with:
          route: GET /repos/{owner}/{repo}/pulls/{pull_number}
          owner: github
          repo: docs
          pull_number: ${{ matrix.number }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Update Branch to latest base ref
        if: ${{ steps.run-or-not.outputs.go-ahead == 'ok' && needs.get-lastsha.outputs.mainsha != fromJSON(steps.get-pull.outputs.data).base.sha && fromJSON(steps.get-pull.outputs.data).state == 'open' }}
        uses: octokit/request-action@v2.x
        id: update-pullbranch-api
        with:
          route: PUT /repos/{owner}/{repo}/pulls/{pull_number}/update-branch
          owner: github
          repo: docs
          pull_number: ${{ matrix.number }}
          mediaType: '{"previews":["lydian"]}'
        env:
          GITHUB_TOKEN: ${{ secrets.GHPAT }} # expires on 3rd Jan 22. please remember to refresh.
  
  
