name: Print Xcode Version
on:
  push:
    paths-ignore:
      - '.github/action-files/**'

jobs:
  print-version:
    runs-on: macos-latest
    steps:
      - run: xcode-select -p
      - run: xcrun -find xcodebuild